### ISSUE TITLE
Finalize basic Capabilities

### ISSUE THREAD

**Issue by s-kostyuk** [s-kostyuk/everpl#88]
- [x] Finalize the list of basic Capabilities such as On/Off, Open/Closed, Is Active and so on
- [x] Finalize the naming scheme of Capabilities - #86 
- [x] Document all basic Capabilities - #89
- [x] Change Thing implementations according to the new Capabilities - #85 
- [x] Prepare everything needed to be able to list all Capabilities supported by a Thing in client views - #87

**Comment by s-kostyuk** [comment]
Everything is completed - Closed
